### ISSUE TITLE
Issues running on my database

### ISSUE THREAD

**Issue by threeaccents** [coleifer/sqlite-web#107]
I'm trying to run sqlite_web on my current database. While trying to the application I get this error.

```bash
[rodrigo@staging hub]$ sqlite_web db
Traceback (most recent call last):
  File "/home/rodrigo/.local/bin/sqlite_web", line 33, in <module>
    sys.exit(load_entry_point('sqlite-web==0.4.0', 'console_scripts', 'sqlite_web')())
  File "/home/rodrigo/.local/lib/python3.10/site-packages/sqlite_web/sqlite_web.py", line 870, in main
    initialize_app(args[0], options.read_only, password, options.url_prefix,
  File "/home/rodrigo/.local/lib/python3.10/site-packages/sqlite_web/sqlite_web.py", line 837, in initialize_app
    dataset = SqliteDataSet('sqlite:///%s' % filename, bare_fields=True)
  File "/home/rodrigo/.local/lib/python3.10/site-packages/playhouse/dataset.py", line 49, in __init__
    self._models = self._introspector.generate_models(
  File "/home/rodrigo/.local/lib/python3.10/site-packages/playhouse/reflection.py", line 679, in generate_models
    database = self.introspect(table_names, literal_column_names,
  File "/home/rodrigo/.local/lib/python3.10/site-packages/playhouse/reflection.py", line 663, in introspect
    src.set_foreign_key(
  File "/home/rodrigo/.local/lib/python3.10/site-packages/playhouse/reflection.py", line 131, in set_foreign_key
    self.rel_model = model_names[foreign_key.dest_table]
KeyError: 'plant_id'
```

`plant_id` is a column in one of my tables.

**Comment by coleifer** [comment]
Your schema may be busted. Please share the schema. You can get this by opening your database with SQLite shell and typing ".schema"

**Comment by coleifer** [comment]
I will reopen once you've shared the schema and can verify this is an issue.

**Comment by threeaccents** [comment]
```bash
CREATE TABLE IF NOT EXISTS "schema_migrations" ("version" INTEGER PRIMARY KEY, "inserted_at" TEXT_DATETIME);
CREATE TABLE IF NOT EXISTS "users" ("id" TEXT_UUID PRIMARY KEY, "first_name" TEXT NOT NULL, "last_name" TEXT, "phone_number" TEXT NOT NULL COLLATE NOCASE, "hashed_password" TEXT NOT NULL, "confirmed_at" TEXT_DATETIME, "inserted_at" TEXT_DATETIME NOT NULL, "updated_at" TEXT_DATETIME NOT NULL, "is_admin" BOOLEAN DEFAULT false NOT NULL, "selected_language" TEXT DEFAULT 'english' NOT NULL);
CREATE UNIQUE INDEX "users_phone_number_index" ON "users" ("phone_number");
CREATE TABLE IF NOT EXISTS "user_tokens" ("id" TEXT_UUID PRIMARY KEY, "user_id" TEXT_UUID NOT NULL CONSTRAINT "user_tokens_user_id_fkey" REFERENCES "users"("id") ON DELETE CASCADE, "token" BLOB NOT NULL, "context" TEXT NOT NULL, "sent_to" TEXT, "inserted_at" TEXT_DATETIME NOT NULL);
CREATE INDEX "user_tokens_user_id_index" ON "user_tokens" ("user_id");
CREATE UNIQUE INDEX "user_tokens_context_token_index" ON "user_tokens" ("context", "token");
CREATE TABLE IF NOT EXISTS "crops" ("id" TEXT_UUID PRIMARY KEY, "name" TEXT NOT NULL, "media_urls" JSON, "measurement_unit" TEXT DEFAULT 'weight_in_lbs' NOT NULL, "inserted_at" TEXT_DATETIME NOT NULL, "updated_at" TEXT_DATETIME NOT NULL);
CREATE UNIQUE INDEX "crops_name_index" ON "crops" ("name");
CREATE TABLE IF NOT EXISTS "harvests" ("id" TEXT_UUID PRIMARY KEY, "name" TEXT NOT NULL, "media_urls" JSON, "notes" TEXT, "harvested_on" TEXT_DATETIME NOT NULL, "inserted_at" TEXT_DATETIME NOT NULL, "updated_at" TEXT_DATETIME NOT NULL);
CREATE UNIQUE INDEX "harvests_name_index" ON "harvests" ("name");
CREATE TABLE IF NOT EXISTS "harvest_yields" ("id" TEXT_UUID PRIMARY KEY, "harvest_id" TEXT_UUID NOT NULL CONSTRAINT "harvest_yields_harvest_id_fkey" REFERENCES "harvests"("id"), "crop_id" TEXT_UUID NOT NULL CONSTRAINT "harvest_yields_crop_id_fkey" REFERENCES "crops"("id"), "quantity" INTEGER NOT NULL, "media_urls" JSON, "inserted_at" TEXT_DATETIME NOT NULL, "updated_at" TEXT_DATETIME NOT NULL);
CREATE TABLE IF NOT EXISTS "trees" ("id" TEXT_UUID PRIMARY KEY, "name" TEXT NOT NULL, "media_urls" JSON NOT NULL, "category" TEXT NOT NULL, "description" TEXT NOT NULL, "inserted_at" TEXT_DATETIME NOT NULL, "updated_at" TEXT_DATETIME NOT NULL, "price" INTEGER NOT NULL);
CREATE UNIQUE INDEX "trees_name_index" ON "trees" ("name");
CREATE TABLE IF NOT EXISTS "plants" ("id" TEXT_UUID PRIMARY KEY, "name" TEXT NOT NULL, "media_urls" JSON NOT NULL, "inserted_at" TEXT_DATETIME NOT NULL, "updated_at" TEXT_DATETIME NOT NULL);
CREATE UNIQUE INDEX "plants_name_index" ON "plants" ("name");
CREATE TABLE IF NOT EXISTS "adoptions" ("id" TEXT_UUID PRIMARY KEY, "name" TEXT NOT NULL, "date" TEXT_DATETIME NOT NULL, "adopter_id" TEXT_UUID NOT NULL CONSTRAINT "adoptions_adopter_id_fkey" REFERENCES "users"("id"), "media" JSON DEFAULT ('{}'), "inserted_at" TEXT_DATETIME NOT NULL, "updated_at" TEXT_DATETIME NOT NULL);
CREATE TABLE IF NOT EXISTS "adoption_tree" ("id" TEXT_UUID PRIMARY KEY, "adoption_id" TEXT_UUID NOT NULL CONSTRAINT "adoption_tree_adoption_id_fkey" REFERENCES "adoptions"("id"), "tree_id" TEXT_UUID NOT NULL CONSTRAINT "adoption_tree_tree_id_fkey" REFERENCES "trees"("id"), "qty" INTEGER NOT NULL);
CREATE UNIQUE INDEX "adoption_tree_adoption_id_tree_id_index" ON "adoption_tree" ("adoption_id", "tree_id");
CREATE TABLE IF NOT EXISTS "adoption_plant" ("id" TEXT_UUID PRIMARY KEY, "adoption_id" TEXT_UUID NOT NULL CONSTRAINT "adoption_plant_adoption_id_fkey" REFERENCES "adoptions"("id"), "plant_id" TEXT_UUID NOT NULL CONSTRAINT "adoption_plant_plant_id_fkey" REFERENCES "plant_id"("id"), "qty" INTEGER NOT NULL);
CREATE UNIQUE INDEX "adoption_plant_adoption_id_plant_id_index" ON "adoption_plant" ("adoption_id", "plant_id");
CREATE TABLE IF NOT EXISTS "temp_adoptions" ("id" TEXT_UUID PRIMARY KEY, "data" BLOB, "inserted_at" TEXT_DATETIME NOT NULL, "updated_at" TEXT_DATETIME NOT NULL);
```

**Comment by coleifer** [comment]
This is incorrect:

```sql
CREATE TABLE IF NOT EXISTS "adoption_plant" (
    "id" TEXT_UUID PRIMARY KEY, "adoption_id" TEXT_UUID NOT NULL 
        CONSTRAINT "adoption_plant_adoption_id_fkey" REFERENCES "adoptions"("id"),
    "plant_id" TEXT_UUID NOT NULL 
        CONSTRAINT "adoption_plant_plant_id_fkey" 
        REFERENCES "plant_id"("id"), "qty" INTEGER NOT NULL);
```

There is no table `plant_id` - probably it should be `plants`?
