### ISSUE TITLE
There is error when I drop the only column of a table

### ISSUE THREAD

**Issue by teddyxiong53** [coleifer/sqlite-web#109]
Hi coleifer,

I create a table, it has a default id column.
I want to delete it because I want to use my own sid.
But there is such error when I delete the id colume directly(It would be OK if I create the sid column before I delete the id column)
```
Traceback (most recent call last):
  File "/home/hanliang.xiong/.local/lib/python3.8/site-packages/peewee.py", line 3237, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: near ")": syntax error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hanliang.xiong/.local/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hanliang.xiong/.local/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hanliang.xiong/.local/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hanliang.xiong/.local/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/hanliang.xiong/.local/lib/python3.8/site-packages/sqlite_web/sqlite_web.py", line 214, in inner
    return fn(table, *args, **kwargs)
  File "/home/hanliang.xiong/.local/lib/python3.8/site-packages/sqlite_web/sqlite_web.py", line 310, in drop_column
    migrate(migrator.drop_column(table, name))
  File "/home/hanliang.xiong/.local/lib/python3.8/site-packages/playhouse/migrate.py", line 886, in migrate
    operation.run()
  File "/home/hanliang.xiong/.local/lib/python3.8/site-packages/playhouse/migrate.py", line 164, in run
    self._handle_result(method(*self.args, **kwargs))
  File "/home/hanliang.xiong/.local/lib/python3.8/site-packages/playhouse/migrate.py", line 155, in _handle_result
    result.run()
  File "/home/hanliang.xiong/.local/lib/python3.8/site-packages/playhouse/migrate.py", line 164, in run
    self._handle_result(method(*self.args, **kwargs))
  File "/home/hanliang.xiong/.local/lib/python3.8/site-packages/playhouse/migrate.py", line 158, in _handle_result
    self._handle_result(item)
  File "/home/hanliang.xiong/.local/lib/python3.8/site-packages/playhouse/migrate.py", line 153, in _handle_result
    self.execute(result)
  File "/home/hanliang.xiong/.local/lib/python3.8/site-packages/playhouse/migrate.py", line 149, in execute
    self.migrator.database.execute(node)
  File "/home/hanliang.xiong/.local/lib/python3.8/site-packages/peewee.py", line 3250, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/home/hanliang.xiong/.local/lib/python3.8/site-packages/peewee.py", line 3244, in execute_sql
    self.commit()
  File "/home/hanliang.xiong/.local/lib/python3.8/site-packages/peewee.py", line 3010, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/home/hanliang.xiong/.local/lib/python3.8/site-packages/peewee.py", line 192, in reraise
    raise value.with_traceback(tb)
  File "/home/hanliang.xiong/.local/lib/python3.8/site-packages/peewee.py", line 3237, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: near ")": syntax error
```

**Comment by coleifer** [comment]
Yeah, you cannot have a table with no columns. Add your column first, then drop. Or rename the "id" to the new name (provided the type is the same).
