### ISSUE TITLE
docker build fails

### ISSUE THREAD

**Issue by terion-name** [coleifer/sqlite-web#115]
docker-compose:
```yml
services:
  dbviewer:
    build: https://github.com/coleifer/sqlite-web.git#55e874d93dd8e76a00275e526ded051411525924:docker # latest commit
```

```
Collecting peewee
  Downloading https://files.pythonhosted.org/packages/f2/a9/61d0cd8861fb62abb9d6fd93ca848e46bdfe3d96299f0f76931f06c1cbfb/peewee-3.16.1.tar.gz (868kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  Complete output from command /usr/local/bin/python /usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp84_pqknf:
  Traceback (most recent call last):
    File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
      main()
    File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-dnz0s9ey/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-dnz0s9ey/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-dnz0s9ey/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 335, in run_setup
      exec(code, locals())
    File "<string>", line 196, in <module>
    File "<string>", line 150, in _do_setup
  ModuleNotFoundError: No module named 'peewee'
  
  ----------------------------------------
Command "/usr/local/bin/python /usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp84_pqknf" failed with error code 1 in /tmp/pip-install-iz43s35v/peewee
You are using pip version 19.0.1, however version 23.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The command '/bin/sh -c apk update       && apk add --no-cache --virtual .build-deps build-base libressl coreutils gcc libc-dev linux-headers make tar wget tcl tcl-dev dpkg dpkg-dev       && wget https://www.sqlite.org/src/tarball/sqlite.tar.gz?r=release -O sqlite.tar.gz -q       && tar xzf sqlite.tar.gz       && cd sqlite       && buildArch="$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)"       && LIBS="-lm" PREFIX="/usr/local" ./configure --build="$buildArch" --disable-tcl --enable-shared --enable-static --enable-tempstore=always --prefix="/usr/local"       && make -j4       && make install       && cd ../       && rm -rf ./sqlite/ ./sqlite.tar.gz       && pip install --no-cache-dir cython       && pip install --no-cache-dir flask peewee sqlite-web       && apk del .build-deps' returned a non-zero code: 1
ERROR: Service 'dbviewer' failed to build : Build failed

```

**Comment by coleifer** [comment]
The people at @pypa are so awful, thanks for finding and fixing this!
