### ISSUE TITLE
Content tab throws 500 Internal Service error

### ISSUE THREAD

**Issue by jeremyvoltz** [coleifer/sqlite-web#12]
Happening on every table.  The structure and query tabs work though.

**Comment by coleifer** [comment]
Weird, can you try running with `-d` for DEBUG and pasting the traceback?

**Comment by jeremyvoltz** [comment]
AttributeError
AttributeError: 'ModelOptions' object has no attribute 'get_fields'

Traceback (most recent call last)
File "/Users/jeremyvoltz/Downloads/flask-admin-test/env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
return self.wsgi_app(environ, start_response)
File "/Users/jeremyvoltz/Downloads/flask-admin-test/env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/Users/jeremyvoltz/Downloads/flask-admin-test/env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
reraise(exc_type, exc_value, tb)
File "/Users/jeremyvoltz/Downloads/flask-admin-test/env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "/Users/jeremyvoltz/Downloads/flask-admin-test/env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/Users/jeremyvoltz/Downloads/flask-admin-test/env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/Users/jeremyvoltz/Downloads/flask-admin-test/env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "/Users/jeremyvoltz/Downloads/flask-admin-test/env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/Users/jeremyvoltz/Downloads/flask-admin-test/env/lib/python2.7/site-packages/sqlite_web/sqlite_web.py", line 177, in inner
return fn(table, *args, **kwargs)
File "/Users/jeremyvoltz/Downloads/flask-admin-test/env/lib/python2.7/site-packages/sqlite_web/sqlite_web.py", line 408, in table_content
for field in ds_table.model_class._meta.get_fields()]
AttributeError: 'ModelOptions' object has no attribute 'get_fields'

**Comment by coleifer** [comment]
I think you may just need to upgrade `sqlite-web` and `peewee`. Can you run `pip install -U sqlite-web peewee` and let me know if that fixes things? Also thanks for the quick response.

**Comment by coleifer** [comment]
My guess is you upgraded peewee but sqlite-web is at an older version that doesn't account for some internal API changes that were made in peewee.

**Comment by jeremyvoltz** [comment]
Everything was already up to date, didn't fix the problem.

**Comment by jeremyvoltz** [comment]
It's probably something I've done wrong in defining my models in flask with sqlalchemy, but I'd have no idea what the problem could be.

**Comment by coleifer** [comment]
I can tell by the code in the traceback that your sqlite_web is not the most recent version, so you might try again updating it.

**Comment by coleifer** [comment]
Shoot, you're right -- I did not actually push a new version of sqlite-web. Sorry, just pushed 0.1.5 to pypi that should fix it.

**Comment by coleifer** [comment]
Upgrade sqlite-web and you should be all set. Sorry for my misleading comments, I thought I'd pushed a release already.

**Comment by jeremyvoltz** [comment]
Yep, that did it, thanks!  Also, this is a great project, thanks for making it!
