### ISSUE TITLE
sqlite-web errors when trying to drop a column

### ISSUE THREAD

**Issue by LunarTwilight** [coleifer/sqlite-web#131]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.10/dist-packages/sqlite_web/sqlite_web.py", line 248, in inner
    return fn(table, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sqlite_web/sqlite_web.py", line 347, in drop_column
    migrate(migrator.drop_column(table, name))
  File "/usr/local/lib/python3.10/dist-packages/playhouse/migrate.py", line 886, in migrate
    operation.run()
  File "/usr/local/lib/python3.10/dist-packages/playhouse/migrate.py", line 164, in run
    self._handle_result(method(*self.args, **kwargs))
  File "/usr/local/lib/python3.10/dist-packages/playhouse/migrate.py", line 155, in _handle_result
    result.run()
  File "/usr/local/lib/python3.10/dist-packages/playhouse/migrate.py", line 164, in run
    self._handle_result(method(*self.args, **kwargs))
  File "/usr/local/lib/python3.10/dist-packages/playhouse/migrate.py", line 172, in inner
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/playhouse/migrate.py", line 723, in _update_column
    column_name, = self.column_name_re.match(column_def).groups()
AttributeError: 'NoneType' object has no attribute 'groups'
```
DB schema: (also happens with no primary key too)
```
CREATE TABLE [newTable]  (
  [test] TEXT NULL,
  [test1] TEXT NULL,
  PRIMARY KEY ([test])
)
```
As for the contents of the table, I just put gibberish for each of the rows in the `test` column, for the `test1` column I set the first two rows to NULL and set the last row to gibberish.

**Comment by LunarTwilight** [comment]
Weird, now I can't reproduce it either. I can get an "internal server error" page if I try to drop the only row in a table tho, but there's no stack trace in my logs.
