### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by VIRUXE** [coleifer/sqlite-web#132]
I'm getting a 500 when trying to view tables with diacritics. é ã etc

**Comment by coleifer** [comment]
Please run in debug mode (-d) and share the traceback.

**Comment by VIRUXE** [comment]
OperationalError
sqlite3.OperationalError: Could not decode to UTF-8 column 'message' with text 'vou come�ar a levar as coisas pra la entao'

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.9/site-packages/sqlite_web/sqlite_web.py", line 221, in inner
    return fn(table, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/sqlite_web/sqlite_web.py", line 476, in table_content
    return render_template(
  File "/usr/local/lib/python3.9/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
  File "/usr/local/lib/python3.9/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/local/lib/python3.9/site-packages/sqlite_web/templates/table_content.html", line 1, in top-level template code
    {% extends "base_table.html" %}
  File "/usr/local/lib/python3.9/site-packages/sqlite_web/templates/base_table.html", line 1, in top-level template code
    {% extends "base_tables.html" %}
  File "/usr/local/lib/python3.9/site-packages/sqlite_web/templates/base_tables.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/usr/local/lib/python3.9/site-packages/sqlite_web/templates/base.html", line 62, in top-level template code
    {% block content %}{% endblock %}
  File "/usr/local/lib/python3.9/site-packages/sqlite_web/templates/base_table.html", line 37, in block 'content'
    {% block inner_content %}
  File "/usr/local/lib/python3.9/site-packages/sqlite_web/templates/table_content.html", line 40, in block 'inner_content'
    {% for row in query %}
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 4583, in next
    self.cursor_wrapper.iterate()
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 4494, in iterate
    row = self.cursor.fetchone()
```

**Comment by coleifer** [comment]
Did you use latin1 or some other encoding? That error would seem to indicate that your accented characters are not encoded using utf8.

If that's the case, we don't really bother supporting non-utf8, and I suggest updating your database to use utf8 instead.

**Comment by coleifer** [comment]
As you can see, we handle utf8-encoded unicode just fine. Here there are accented characters in the table name, the column name, and in a row of data:

![im-1694469010927](https://github.com/coleifer/sqlite-web/assets/119974/56aeafbb-dca2-4951-88d5-fd7be1be254a)
![im-1694469018180](https://github.com/coleifer/sqlite-web/assets/119974/2fd33207-d483-443d-b5f9-c75ae1c30990)

**Comment by VIRUXE** [comment]
Data is being inserted directly from a SA-MP gameserver, which I think natively uses windows1252.

```c++
stock SendPrivateMessage(conversationId, playerId, message[]) {
    new playerName[MAX_PLAYER_NAME], otherPlayerName[MAX_PLAYER_NAME];

    GetPlayerName(playerId, playerName, MAX_PLAYER_NAME);
    
    stmt_bind_value(stmt_InsertMessage, 0, DB::TYPE_INTEGER, conversationId);
    stmt_bind_value(stmt_InsertMessage, 1, DB::TYPE_STRING, playerName);
    stmt_bind_value(stmt_InsertMessage, 2, DB::TYPE_STRING, message);

    stmt_execute(stmt_InsertMessage);
```

`stmt_InsertMessage = db_prepare(Database, "INSERT INTO conversation_messages (conversation_id, sender, message) VALUES (?, ?, ?);");`

Goes directly from the game chat or dialog onto that statement.

**Comment by coleifer** [comment]
Yeah we're limited to utf8 at the present, unfortunately.
