### ISSUE TITLE
OperationalError: unable to open database file

### ISSUE THREAD

**Issue by lenisko** [coleifer/sqlite-web#29]
Hello there!

When trying to open already opened database I got this.
Is there any way to add flag which would ignore other connections?
```
$ sqlite_web db.sqlite -H 0.0.0.0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/peewee.py", line 3688, in _create_connection
    return self._connect(self.database, **self.connect_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/peewee.py", line 3939, in _connect
    conn = sqlite3.connect(database, **kwargs)
sqlite3.OperationalError: unable to open database file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/sqlite_web", line 11, in <module>
    load_entry_point('sqlite-web==0.1.6', 'console_scripts', 'sqlite_web')()
  File "/usr/local/lib/python3.5/dist-packages/sqlite_web/sqlite_web.py", line 678, in main
    dataset = SqliteDataSet('sqlite:///%s' % db_file)
  File "/usr/local/lib/python3.5/dist-packages/playhouse/dataset.py", line 31, in __init__
    self._database.connect()
  File "/usr/local/lib/python3.5/dist-packages/peewee.py", line 3660, in connect
    self._local.conn = self._create_connection()
  File "/usr/local/lib/python3.5/dist-packages/peewee.py", line 3688, in _create_connection
    return self._connect(self.database, **self.connect_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/peewee.py", line 3578, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python3.5/dist-packages/peewee.py", line 135, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/peewee.py", line 3688, in _create_connection
    return self._connect(self.database, **self.connect_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/peewee.py", line 3939, in _connect
    conn = sqlite3.connect(database, **kwargs)
peewee.OperationalError: unable to open database file
```

**Comment by coleifer** [comment]
uhmmm.

**Comment by CHOMNANP** [comment]
Having the same issue. Can anyone explain how to get this working?
