### ISSUE TITLE
OperationalError: no such column: t1.id

### ISSUE THREAD

**Issue by erpadmin** [coleifer/sqlite-web#31]
When selecting CONTENT tab for one specific table I get the following error.

```
[2017-05-30 15:59:12,406] ERROR in app: Exception on /GONEUSERS/content/ [GET]
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/sqlite_web/sqlite_web.py", line 185, in inner
    return fn(table, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/sqlite_web/sqlite_web.py", line 436, in table_content
    total_rows=total_rows)
  File "/usr/lib64/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/lib64/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/sqlite_web/templates/table_content.html", line 1, in top-level template code
    {% extends "base_table.html" %}
  File "/usr/lib/python2.7/site-packages/sqlite_web/templates/base_table.html", line 1, in top-level template code
    {% extends "base_tables.html" %}
  File "/usr/lib/python2.7/site-packages/sqlite_web/templates/base_tables.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/usr/lib/python2.7/site-packages/sqlite_web/templates/base.html", line 58, in top-level template code
    {% block content %}{% endblock %}
  File "/usr/lib/python2.7/site-packages/sqlite_web/templates/base_table.html", line 26, in block "content"
    {% block inner_content %}
  File "/usr/lib/python2.7/site-packages/sqlite_web/templates/table_content.html", line 38, in block "inner_content"
    {% for row in query %}
  File "/usr/lib/python2.7/site-packages/peewee.py", line 3240, in __iter__
    return iter(self.execute())
  File "/usr/lib/python2.7/site-packages/peewee.py", line 3233, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/usr/lib/python2.7/site-packages/peewee.py", line 2912, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/usr/lib/python2.7/site-packages/peewee.py", line 3775, in execute_sql
    self.commit()
  File "/usr/lib/python2.7/site-packages/peewee.py", line 3598, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/lib/python2.7/site-packages/peewee.py", line 3768, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: no such column: t1.id
127.0.0.1 - - [30/May/2017 15:59:12] "GET /GONEUSERS/content/ HTTP/1.1" 500 -

```

```
sqlite> .schema goneusers
CREATE TABLE GONEUSERS
       (USERNAME  TEXT     NOT NULL
   );

```

**Comment by coleifer** [comment]
The issue is that Peewee isn't correctly handling the fact that your table doesn't have a primary key...I vaguely recall fixing something similar (not able to browse around at the moment). Have you upgraded to the latest versions of peewee and sqlite-web?

**Comment by erpadmin** [comment]
I doubt they are the latest (Fedora 25).  I have another table that is working and it doesn't have a primary key. Can provide more info tomorrow.

**Comment by erpadmin** [comment]
This table works
```
sqlite> .schema gvallusers
CREATE TABLE GVALLUSERS
       (USERNAME  TEXT     NOT NULL,
    COMMENT   TEXT,
USERID    INT      NOT NULL
   );
```

**Comment by ideaplat** [comment]
File "/usr/local/lib/python3.5/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/sqlite_web/templates/table_content.html", line 1, in top-level template code
    {% extends "base_table.html" %}
  File "/usr/local/lib/python3.5/dist-packages/sqlite_web/templates/base_table.html", line 1, in top-level template code
    {% extends "base_tables.html" %}
  File "/usr/local/lib/python3.5/dist-packages/sqlite_web/templates/base_tables.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/usr/local/lib/python3.5/dist-packages/sqlite_web/templates/base.html", line 58, in top-level template code
    {% block content %}{% endblock %}
  File "/usr/local/lib/python3.5/dist-packages/sqlite_web/templates/base_table.html", line 26, in block "content"
    {% block inner_content %}
  File "/usr/local/lib/python3.5/dist-packages/sqlite_web/templates/table_content.html", line 38, in block "inner_content"
    {% for row in query %}
  File "/usr/local/lib/python3.5/dist-packages/peewee.py", line 3240, in __iter__
    return iter(self.execute())
  File "/usr/local/lib/python3.5/dist-packages/peewee.py", line 3233, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/usr/local/lib/python3.5/dist-packages/peewee.py", line 2912, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/usr/local/lib/python3.5/dist-packages/peewee.py", line 3775, in execute_sql
    self.commit()
  File "/usr/local/lib/python3.5/dist-packages/peewee.py", line 3598, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python3.5/dist-packages/peewee.py", line 135, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/peewee.py", line 3768, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: no such column: t1.id

**Comment by ideaplat** [comment]
ubuntu17.04  python3.5

**Comment by ideaplat** [comment]
Error importing file: iterator should return strings, not bytes (did you open the file in text mode?)

**Comment by coleifer** [comment]
@ideaplat -- what's the error? In your first comment there's an `OperationalError` about a missing `t1.id` column. The 3rd comment has a different issue (I'm not clear where it's coming from as you did not include the full traceback). Can you provide more context / info?

**Comment by WolfgangFahl** [comment]
The same error makes my sqlite_web still choke. Is there now way to ignore non working tables and continue?
