### ISSUE TITLE
error message in use

### ISSUE THREAD

**Issue by scargill** [coleifer/sqlite-web#50]
Running - but 
----------------------------------------
192.168.1.31 - - [18/Sep/2018 14:14:31] "GET /timeseries/content/ HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('192.168.1.31', 54295)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------

**Comment by coleifer** [comment]
Not sure, maybe it's timing out or something.
