### ISSUE TITLE
Docker container does not start

### ISSUE THREAD

**Issue by mmccllm** [coleifer/sqlite-web#54]
After building the docker container it fails to run:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 2683, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: no such module: spellfix1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/sqlite_web", line 11, in <module>
    load_entry_point('sqlite-web==0.3.5', 'console_scripts', 'sqlite_web')()
  File "/usr/local/lib/python3.7/site-packages/sqlite_web/sqlite_web.py", line 818, in main
    initialize_app(args[0], options.read_only, password, options.url_prefix)
  File "/usr/local/lib/python3.7/site-packages/sqlite_web/sqlite_web.py", line 789, in initialize_app
    dataset = SqliteDataSet('sqlite:///%s' % filename, bare_fields=True)
  File "/usr/local/lib/python3.7/site-packages/playhouse/dataset.py", line 44, in __init__
    bare_fields=bare_fields)
  File "/usr/local/lib/python3.7/site-packages/playhouse/reflection.py", line 619, in generate_models
    include_views)
  File "/usr/local/lib/python3.7/site-packages/playhouse/reflection.py", line 524, in introspect
    table_columns = self.metadata.get_columns(table, self.schema)
  File "/usr/local/lib/python3.7/site-packages/playhouse/reflection.py", line 161, in get_columns
    for metadata in self.database.get_columns(table, schema))
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 3176, in get_columns
    (schema or 'main', table))
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 2690, in execute_sql
    self.commit()
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 2481, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 178, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 2683, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: no such module: spellfix1

**Comment by coleifer** [comment]
The database you are trying to access -- does it use the spellfix1 SQLite extension?

**Comment by coleifer** [comment]
I've tested the docker image again locally and verified that it works in general.

If you need to support the spellfix1 extension, then you may have some work to do building a custom docker image, since spellfix1 needs to be compiled separately.
