### ISSUE TITLE
UnicodeDecodeError trying to export data result set as CSV

### ISSUE THREAD

**Issue by gmork** [coleifer/sqlite-web#55]
See Stack Trace below. Happens when clicking the "Export CSV" button on a result set. 

```[2018-11-07 15:51:19,125] ERROR in app: Exception on /Message/query/ [POST]
Traceback (most recent call last):
  File "/Users/gmork/Library/Python/2.7/lib/python/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/gmork/Library/Python/2.7/lib/python/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/gmork/Library/Python/2.7/lib/python/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/gmork/Library/Python/2.7/lib/python/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/gmork/Library/Python/2.7/lib/python/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/gmork/Library/Python/2.7/lib/python/site-packages/sqlite_web/sqlite_web.py", line 210, in inner
    return fn(table, *args, **kwargs)
  File "/Users/gmork/Library/Python/2.7/lib/python/site-packages/sqlite_web/sqlite_web.py", line 473, in table_query
    return export(table, sql, 'csv')
  File "/Users/gmork/Library/Python/2.7/lib/python/site-packages/sqlite_web/sqlite_web.py", line 527, in export
    dataset.freeze(query, export_format, file_obj=buf, **kwargs)
  File "/Users/gmork/Library/Python/2.7/lib/python/site-packages/playhouse/dataset.py", line 152, in freeze
    exporter.export(file_obj, **kwargs)
  File "/Users/gmork/Library/Python/2.7/lib/python/site-packages/playhouse/dataset.py", line 338, in export
    writer.writerow(row)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u20ac' in position 120: ordinal not in range(128)```

**Comment by coleifer** [comment]
Python 2.7 has shit support for writing csv as utf8. You have to essentially write to an in-memory byte buffer (BytesIO) and then pull from that buffer and write to the file manually. See: https://docs.python.org/2/library/csv.html

What I've done is added some tests to the Peewee library that is being used behind-the-scenes, to ensure that unicode data can be written and read correctly when using Python3 and csv. Python 2.x, however, does not support unicode+csv. For python 2.x you can, however, use unicode+json.
