### ISSUE TITLE
Blob type not supported

### ISSUE THREAD

**Issue by ZRunner** [coleifer/sqlite-web#73]
Hello,

For one of my projects I use blob columns to store integer arrays and dictionaries, but it looks like sqlite-web doesn't support that kind of data. Everything was working find until I filled one of these values, and now I can only get the 500 error.

### Full traceback:
```
ERROR in app: Exception on /rss_flows/content/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/site-packages/sqlite_web/sqlite_web.py", line 214, in inner
    return fn(table, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlite_web/sqlite_web.py", line 452, in table_content
    return render_template(
  File "/usr/local/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/usr/local/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/site-packages/sqlite_web/templates/table_content.html", line 1, in top-level template code
    {% extends "base_table.html" %}
  File "/usr/local/lib/python3.8/site-packages/sqlite_web/templates/base_table.html", line 1, in top-level template code
    {% extends "base_tables.html" %}
  File "/usr/local/lib/python3.8/site-packages/sqlite_web/templates/base_tables.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/usr/local/lib/python3.8/site-packages/sqlite_web/templates/base.html", line 62, in top-level template code
    {% block content %}{% endblock %}
  File "/usr/local/lib/python3.8/site-packages/sqlite_web/templates/base_table.html", line 29, in block "content"
    {% block inner_content %}
  File "/usr/local/lib/python3.8/site-packages/sqlite_web/templates/table_content.html", line 39, in block "inner_content"
    {% for row in query %}
  File "/usr/local/lib/python3.8/site-packages/peewee.py", line 4329, in next
    self.cursor_wrapper.iterate()
  File "/usr/local/lib/python3.8/site-packages/peewee.py", line 4248, in iterate
    result = self.process_row(row)
  File "/usr/local/lib/python3.8/site-packages/peewee.py", line 7365, in process_row
    result[attr] = converters[i](row[i])
  File "/usr/local/lib/python3.8/site-packages/peewee.py", line 4496, in python_value
    return value if value is None else self.adapt(value)
  File "/usr/local/lib/python3.8/site-packages/peewee.py", line 4644, in adapt
    return value.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdb in position 0: invalid continuation byte
127.0.0.1 - - [20/Feb/2021 22:04:13] "GET /rss_flows/content/ HTTP/1.1" 500 -
```

### Installation info:
* pip 21.0.1 from Python 3.9.1
* sqlite-web version 0.3.7
* Flask 1.1.2, peewee 3.14.1, Werkzeug 1.0.1
* Running on macOS 11.2.1

Tell me if you need anything else!

**Comment by coleifer** [comment]
It seems like your column is being introspected as a text type rather than a blob in this case, as the error is not coming from sqlite-web (which can handle BLOBs just fine). Rather the error is coming from the peewee model attempting to decode your data as UTF8 text. It will do this only for text fields and not blob fields, so this makes me think either:

* you're storing binary data in a text column
* something weird about the way you've identified the datatype in your schema is causing peewee to think it's a text field

Can you share the schema for the particular table as it appears to sqlite? Sqlite shell ".schema" should give you the info.

**Comment by ZRunner** [comment]
Got it, thanks a lot.
After looking at the table scheme, it looks like a blob column was still using the "text" type, hence the issue. The column edition I did earlier probably didn't went through. Recreating the table fixed it.

Issue closed!
