### ISSUE TITLE
Raspberry Pi3 issues

### ISSUE THREAD

**Issue by pompushko** [coleifer/sqlite-web#82]
Hello, installed successfully , but cannot launch...

```
pi@ra:~ $ whereis sqlite_web
sqlite_web:
```

```
 python3 -m sqlite_web -x -d -H 192.168.100.35 -r static/database/main.sqlite 

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/.local/lib/python3.7/site-packages/sqlite_web/__main__.py", line 1, in <module>
    from sqlite_web import main
ImportError: cannot import name 'main' from 'sqlite_web' (/home/pi/.local/lib/python3.7/site-packages/sqlite_web/__init__.py)
```

**Comment by coleifer** [comment]
This surely has nothing to do with raspberry pi. Whatever the case, questions like this belong on stackoverflow and not the issue tracker.
