### ISSUE TITLE
UndefinedError: 'virtual_tables' is undefined

### ISSUE THREAD

**Issue by jblang** [coleifer/sqlite-web#83]
I get this error on Debian Buster. I'm using the distro's stock version of python 3. sqlite_web and its dependencies were installed via pip.  See below for environmental information and steps to reproduce.

```
$ python --version
Python 3.7.3

$ python -c "import sqlite3; print(sqlite3.sqlite_version)"
3.27.2

$ pip freeze | egrep 'sqlite-web|Flask|peewee|Pygments|click|Jinja2|Werkzeug|itsdangerous|importlib-metadata
|MarkupSafe|typing-extensions|zipp'
click==8.0.1
Flask==2.0.1
importlib-metadata==4.2.0
itsdangerous==2.0.1
Jinja2==3.0.1
MarkupSafe==2.0.1
peewee==3.14.4
Pygments==2.9.0
sqlite-web==0.3.7
typing-extensions==3.10.0.0
Werkzeug==2.0.1
zipp==3.4.1

$ sqlite3 test.db
SQLite version 3.27.2 2019-02-25 16:06:06
Enter ".help" for usage hints.
sqlite> create table dummy (a text, b text, c text);

$ sqlite_web test.db
 * Serving Flask app 'sqlite_web.sqlite_web' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
[2021-05-26 14:33:27,209] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/jblangston/.local/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jblangston/.local/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jblangston/.local/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jblangston/.local/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/jblangston/.local/lib/python3.7/site-packages/sqlite_web/sqlite_web.py", line 193, in index
    return render_template('index.html', sqlite=sqlite3)
  File "/home/jblangston/.local/lib/python3.7/site-packages/flask/templating.py", line 150, in render_template
    ctx.app,
  File "/home/jblangston/.local/lib/python3.7/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/jblangston/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/jblangston/.local/lib/python3.7/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/jblangston/.local/lib/python3.7/site-packages/sqlite_web/templates/index.html", line 1, in top-level template code
    {% extends "base_tables.html" %}
  File "/home/jblangston/.local/lib/python3.7/site-packages/sqlite_web/templates/base_tables.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/jblangston/.local/lib/python3.7/site-packages/sqlite_web/templates/base.html", line 52, in top-level template code
    {% block sidebar %}{% endblock %}
  File "/home/jblangston/.local/lib/python3.7/site-packages/sqlite_web/templates/base_tables.html", line 12, in block 'sidebar'
    {% if table_name in virtual_tables %}
jinja2.exceptions.UndefinedError: 'virtual_tables' is undefined
```

**Comment by jblang** [comment]
Removing [this section](https://github.com/coleifer/sqlite-web/blob/master/sqlite_web/templates/base_tables.html#L12-L14) from base_table.html seems to fix the problem. And indeed I do not see virtual_tables is being defined anywhere.
