### ISSUE TITLE
Key Error when opening db on Foreign Key constraint with different case

### ISSUE THREAD

**Issue by ddgflorida** [coleifer/sqlite-web#85]
I have a database I'm testing with: hackernews.db:

D:\temp>sqlite_web hackernews.db
Traceback (most recent call last):
  File "C:\Users\ddgfl\AppData\Local\Programs\Python\Python36\Scripts\sqlite_web-script.py", line 11, in <module>
    load_entry_point('sqlite-web==0.3.8', 'console_scripts', 'sqlite_web')()
  File "c:\users\ddgfl\appdata\local\programs\python\python36\lib\site-packages\sqlite_web\sqlite_web.py", line 859, in main
    initialize_app(args[0], options.read_only, password, options.url_prefix)
  File "c:\users\ddgfl\appdata\local\programs\python\python36\lib\site-packages\sqlite_web\sqlite_web.py", line 830, in initialize_app
    dataset = SqliteDataSet('sqlite:///%s' % filename, bare_fields=True)
  File "c:\users\ddgfl\appdata\local\programs\python\python36\lib\site-packages\playhouse\dataset.py", line 48, in __init__
    **kwargs)
  File "c:\users\ddgfl\appdata\local\programs\python\python36\lib\site-packages\playhouse\reflection.py", line 675, in generate_models
    include_views)
  File "c:\users\ddgfl\appdata\local\programs\python\python36\lib\site-packages\playhouse\reflection.py", line 662, in introspect
    related_name=related_names.get(src))
  File "c:\users\ddgfl\appdata\local\programs\python\python36\lib\site-packages\playhouse\reflection.py", line 130, in set_foreign_key
    self.rel_model = model_names[foreign_key.dest_table]
KeyError: 'hackernews'

D:\temp>sqlite3 hackernews.db
SQLite version 3.31.1 2020-01-27 19:55:54
Enter ".help" for usage hints.
sqlite> .schema
CREATE TABLE HACKERNEWS (
   pk_HACKERNEWS INTEGER NOT NULL PRIMARY KEY,
   "by" varchar(8),
   descendants number,
   id number,
   score number,
   time number,
   title varchar(46),
   type varchar(5),
   url varchar(45), "text" varchar(2000));
CREATE TABLE HACKERNEWS_KIDS (
   pk_HACKERNEWS_KIDS INTEGER NOT NULL PRIMARY KEY,
   kids number, fk_hackernews INTEGER  REFERENCES hackernews(pk_hackernews));
CREATE INDEX ix_HACKERNEWS_KIDS_fk_hackernews ON HACKERNEWS_KIDS(fk_hackernews);

 I tested this and because the REFERENCES does not match the case of the referenced column (pk_HACKERNEWS vs. pk_hackernews), the key error occurs. Can you change your code to ignore case on column names? Excellent work!

**Comment by coleifer** [comment]
Sorry, I do not really intend to change this tooling - I suggest you correct it in your 'hackernews' database.
