### ISSUE TITLE
Support for Run-Time Loadable Extensions?

### ISSUE THREAD

**Issue by nlohmann** [coleifer/sqlite-web#89]
# Introduction

I implemented an SQLite Run-Time Loadable Extensions (https://www.sqlite.org/loadext.html) which implements a virtual table I would like to query with sqlite-web. The extension itself is a dynamic library - in my case called `librtp.so`. In vanilla Python, I can use it with:

```py
import sqlite3
conn = sqlite3.connect('mydata.db')

conn.enable_load_extension(True)
conn.execute("SELECT load_extension('librtp')")
```

That is, on an existing connect, `enable_load_extension(True)` must be called once to allow loading extensions and a `SELECT load_extension` statement must be executed to use the extension.

# Error

When executing

```sh
sqlite_web mydata.db
```

I get the following backtrace:

```
Traceback (most recent call last):
  File "venv/lib/python3.9/site-packages/peewee.py", line 3144, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: no such module: rtp

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "venv/bin/sqlite_web", line 33, in <module>
    sys.exit(load_entry_point('sqlite-web==0.3.8', 'console_scripts', 'sqlite_web')())
  File "venv/lib/python3.9/site-packages/sqlite_web/sqlite_web.py", line 859, in main
    initialize_app(args[0], options.read_only, password, options.url_prefix)
  File "venv/lib/python3.9/site-packages/sqlite_web/sqlite_web.py", line 830, in initialize_app
    dataset = SqliteDataSet('sqlite:///%s' % filename, bare_fields=True)
  File "venv/lib/python3.9/site-packages/playhouse/dataset.py", line 45, in __init__
    self._models = self._introspector.generate_models(
  File "venv/lib/python3.9/site-packages/playhouse/reflection.py", line 674, in generate_models
    database = self.introspect(table_names, literal_column_names,
  File "venv/lib/python3.9/site-packages/playhouse/reflection.py", line 576, in introspect
    table_columns = self.metadata.get_columns(table, self.schema)
  File "venv/lib/python3.9/site-packages/playhouse/reflection.py", line 169, in get_columns
    for metadata in self.database.get_columns(table, schema))
  File "venv/lib/python3.9/site-packages/peewee.py", line 3678, in get_columns
    cursor = self.execute_sql('PRAGMA "%s".table_info("%s")' %
  File "venv/lib/python3.9/site-packages/peewee.py", line 3151, in execute_sql
    self.commit()
  File "venv/lib/python3.9/site-packages/peewee.py", line 2917, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "venv/lib/python3.9/site-packages/peewee.py", line 190, in reraise
    raise value.with_traceback(tb)
  File "venv/lib/python3.9/site-packages/peewee.py", line 3144, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: no such module: rtp
```

# Question

When looking into the code of peewee, it seems extensions are supported, so `enable_load_extension(True)` should be no problem. But how can I make sure the `SELECT load_extension` is executed before any other statement?

**Comment by coleifer** [comment]
This is implemented now. To load extensions, you will want to pass them in when starting-up sqlite-web:

```sh
# Load ext1.so and ext2.so, for example:
sqlite_web my_database.db -e /path/to/ext1.so -e /path/to/ext2.so
```
